#pragma once

#define HYPRSHELL_PLUGIN_NAME "HYPSHELL PLUGIN TEST"

#define HYPRSHELL_PRINT_DEBUG 1
#define HYPRSHELL_SOCKET_PATH "/tmp/hyprland-plugin-socket"

#define HYPRSHELL_OVERVIEW_MOD "Super"
#define HYPRSHELL_OVERVIEW_KEY "super_l"

#define HYPRSHELL_CLOSE R"("CloseSwitch")"
#define HYPRSHELL_OPEN_OVERVIEW R"("OpenOverview")"

#define HYPRSHELL_SWITCH_BIND_COUNT 1
static const char* HYPRSHELL_SWITCH_BIND_KEYS[HYPRSHELL_SWITCH_BIND_COUNT] = { "Tab" };
static const uint32_t HYPRSHELL_SWITCH_BIND_MOD_MASKS[HYPRSHELL_SWITCH_BIND_COUNT] = { HYPRSHELL_MOD_ALT };
static const uint8_t HYPRSHELL_SWITCH_BIND_HOLD_MASKS[HYPRSHELL_SWITCH_BIND_COUNT] = { HYPRSHELL_HOLD_ALT };
static const char* HYPRSHELL_SWITCH_BIND_COMMANDS[HYPRSHELL_SWITCH_BIND_COUNT] = { R"({"OpenSwitch":{"reverse":false,"profile":0,"hold_mods":["alt"]}})" };
