name: test

on:
  push:
    branches-ignore:
      - "release-please-**"
      - "hyprshell-release"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-nix:
    name: Run Nix Flake Check
    runs-on: "ubuntu-26.04"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          sudo apt update
          sudo apt -y install --no-install-recommends meson ninja-build python3 valac libgtk-4-dev libadwaita-1-dev libpango1.0-dev libgtk4-layer-shell-dev gobject-introspection zstd
          rustup default stable
          cargo build

          failed=0
          cargo xtask check || failed=1
          cargo xtask lint || failed=1
          cargo xtask test --no-nextest || failed=1
          exit "$failed"

      # run: nix build '.#checks.x86_64-linux.hyprshell-check-nix-configs' -L
      # - name: Run Nix Flake Check check-nix-configs
      # - name: Run Nix Flake Check check-all-feature-combinations
      # run: nix build '.#checks.x86_64-linux.hyprshell-check-all-feature-combinations' -L

  check:
    name: Run build tests
    runs-on: "ubuntu-26.04"
    container:
      image: ghcr.io/h3rmt/actions-image:latest
      options: --privileged
    if: github.ref == 'refs/heads/hyprshell'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: rustup default stable
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: hyprshell
          cache-on-failure: true
      - name: Build binary for x86_64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell.sh
          ./scripts/ci/build-x86.sh
      - name: Build binary for aarch64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell-aarch64.sh
          ./scripts/ci/build-aarch64.sh
