name: test

on:
  push:
    branches-ignore:
      - "release-please-**"
      - "hyprshell-release"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-nix:
    name: Run Nix Flake Check
    runs-on: "ubuntu-26.04"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: |
          sudo apt update
          sudo apt -y install --no-install-recommends meson ninja-build python3 valac libgtk-4-dev libadwaita-1-dev libpango1.0-dev libgtk4-layer-shell-dev gobject-introspection libgbm-dev zstd libdbus-1-dev
          rustup default stable

          failed=0
          cargo build || failed=1
          cargo xtask cmd check -v --locked || failed=1
          cargo xtask cmd lint -v || failed=1
          cargo xtask cmd test -v --no-nextest --locked || failed=1
          exit "$failed"

      # run: nix build '.#checks.x86_64-linux.hyprshell-check-nix-configs' -L
      # run: nix build '.#checks.x86_64-linux.hyprshell-check-all-feature-combinations' -L

  check:
    name: Run build tests
    runs-on: "ubuntu-26.04"
    container:
      image: ghcr.io/h3rmt/actions-image:latest
      options: --privileged
    if: github.ref == 'refs/heads/hyprshell'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: rustup default stable
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: hyprshell
          cache-on-failure: true
      - name: Build binary for x86_64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell.sh
          ./scripts/ci/build-x86.sh
      - name: Build binary for aarch64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell-aarch64.sh
          ./scripts/ci/build-aarch64.sh
